{
    "memberid":"cool",
    "membername":"COOL",
    "age":27,
    "program":["java", 
            "python", 
            "javascript"],
    "dept":{
        "deptname":"search",
        "job":"programer"
    }
}